name       : haskell-scientific
version    : 0.3.4.9
release    : 2
source     :
    - http://hackage.haskell.org/package/scientific-0.3.4.9/scientific-0.3.4.9.tar.gz : 108330662b0af9a04d7da55864211ce12008efe36614d897ba635e80670918a8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Data.Scientific provides the number type Scientific. Scientific numbers
    are arbitrary precision and space efficient. They are represented using scientific
    notation.
description: |
    Data.Scientific provides the number type Scientific. Scientific numbers are arbitrary precision and space efficient. They are represented using scientific notation.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-hashable
    - haskell-integer-simple
    - haskell-text
    - haskell-vector
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
