name       : haskell-scientific
version    : 0.3.6.2
release    : 5
source     :
    - https://hackage.haskell.org/package/scientific-0.3.6.2/scientific-0.3.6.2.tar.gz : 278d0afc87450254f8a76eab21b5583af63954efc9b74844a17a21a68013140f
license    : BSD-3-Clause
component  : programming.haskell
summary    : Data.Scientific provides the number type Scientific. Scientific numbers
    are arbitrary precision and space efficient. They are represented using scientific
    notation.
description: |
    Data.Scientific provides the number type Scientific. Scientific numbers are arbitrary precision and space efficient. They are represented using scientific notation.
builddeps  :
    - haskell-cabal-install
    - haskell-hashable-devel
    - haskell-integer-logarithms-devel
    - haskell-primitive-devel
rundeps    :
    - devel:
        - haskell-hashable-devel
        - haskell-integer-logarithms-devel
        - haskell-primitive-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
