name       : haskell-scientific
version    : 0.3.4.9
release    : 1
source     :
    - http://hackage.haskell.org/package/scientific-0.3.4.9/scientific-0.3.4.9.tar.gz : 108330662b0af9a04d7da55864211ce12008efe36614d897ba635e80670918a8
license    : BSD-3-Clause
component  : programming
summary    : Data.Scientific provides the number type Scientific. Scientific numbers are arbitrary precision and space efficient. They are represented using scientific notation.
description: |
    Data.Scientific provides the number type Scientific. Scientific numbers are arbitrary precision and space efficient. They are represented using scientific notation.
builddeps  :
    - ghc
    - haskell-hashable
    - haskell-integer-simple
    - haskell-text
    - haskell-vector
setup      : |
    sudo ghc-pkg recache
    ghc -threaded --make Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 scientific-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/scientific-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/scientific-$version/*.a
